"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['clipycards.py']
APP_NAME = "ClipyCards"
DATA_FILES = []
OPTIONS = {
    'iconfile': 'icon.icns',
    'packages':['json', 'faiss', 'numpy', 'openai', 'logging', 'traceback', 're', 'csv', 'pyperclip', 'customtkinter'],
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "Creating info cards",
        'CFBundleVersion': "0.1.0",
        'CFBundleShortVersionString': "0.1.0",
        'NSHumanReadableCopyright': u"Copyright © 2024 MohSilas, GNU General Public License."
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
